sequenceDiagram
  participant participant_createInfraSecretStoreAdapter as createInfraSecretStoreAdapter
  participant participant_createSupabaseVaultAdapter as createSupabaseVaultAdapter
  participant_createInfraSecretStoreAdapter->>participant_createSupabaseVaultAdapter: createSupabaseVaultAdapter()
  participant_createSupabaseVaultAdapter-->>participant_createInfraSecretStoreAdapter: return
