sequenceDiagram
  participant participant_normalizeAuthCallbackRoute as normalizeAuthCallbackRoute
  participant participant_normalizeCallbackRoute as normalizeCallbackRoute
  participant_normalizeAuthCallbackRoute->>participant_normalizeCallbackRoute: normalizeCallbackRoute()
  participant_normalizeCallbackRoute-->>participant_normalizeAuthCallbackRoute: return
