graph LR
  module_src_adapters_minikube_auth_index_ts["src/adapters/minikube/auth/index.ts"]
  module_src_adapters_minikube_auth_supabase_index_ts["src/adapters/minikube/auth/supabase/index.ts"]
  module_src_adapters_minikube_authz_cerbos_index_ts["src/adapters/minikube/authz/cerbos/index.ts"]
  module_src_adapters_minikube_authz_index_ts["src/adapters/minikube/authz/index.ts"]
  module_src_adapters_minikube_base_index_ts["src/adapters/minikube/base/index.ts"]
  module_src_adapters_minikube_contracts_ts["src/adapters/minikube/contracts.ts"]
  module_src_adapters_minikube_index_ts["src/adapters/minikube/index.ts"]
  module_src_adapters_minikube_storage_index_ts["src/adapters/minikube/storage/index.ts"]
  module_src_adapters_minikube_storage_supabase_index_ts["src/adapters/minikube/storage/supabase/index.ts"]
  module_src_apis_ts["src/apis.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_types_ts["src/types.ts"]
  module_src_adapters_minikube_auth_index_ts --> module_src_adapters_minikube_auth_supabase_index_ts
  module_src_adapters_minikube_auth_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_adapters_minikube_auth_index_ts --> module_src_types_ts
  module_src_adapters_minikube_auth_supabase_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_adapters_minikube_auth_supabase_index_ts --> module_src_types_ts
  module_src_adapters_minikube_authz_cerbos_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_adapters_minikube_authz_cerbos_index_ts --> module_src_types_ts
  module_src_adapters_minikube_authz_index_ts --> module_src_adapters_minikube_authz_cerbos_index_ts
  module_src_adapters_minikube_authz_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_adapters_minikube_authz_index_ts --> module_src_types_ts
  module_src_adapters_minikube_base_index_ts --> module_src_types_ts
  module_src_adapters_minikube_contracts_ts --> module_src_types_ts
  module_src_adapters_minikube_index_ts --> module_src_adapters_minikube_auth_index_ts
  module_src_adapters_minikube_index_ts --> module_src_adapters_minikube_authz_index_ts
  module_src_adapters_minikube_index_ts --> module_src_adapters_minikube_base_index_ts
  module_src_adapters_minikube_index_ts --> module_src_adapters_minikube_storage_index_ts
  module_src_adapters_minikube_index_ts --> module_src_apis_ts
  module_src_adapters_minikube_index_ts --> module_src_types_ts
  module_src_adapters_minikube_storage_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_adapters_minikube_storage_index_ts --> module_src_adapters_minikube_storage_supabase_index_ts
  module_src_adapters_minikube_storage_index_ts --> module_src_types_ts
  module_src_adapters_minikube_storage_supabase_index_ts --> module_src_adapters_minikube_contracts_ts
  module_src_apis_ts --> module_src_types_ts
  module_src_index_ts --> module_src_adapters_minikube_index_ts
  module_src_index_ts --> module_src_types_ts
